### ISSUE TITLE
testtargetmodel can't find the corresponding definition

### ISSUE THREAD

**Issue by Chrisable** [lmgraves/AmnesiacML#2]
What is the testtargetmodel in r, m = testtargetmodel()?
![image](https://user-images.githubusercontent.com/49330390/159681842-7ed12ea9-a238-4095-83ec-254e612c5ff0.png)

I can't find the corresponding definition.
Is this the complete code?

**Comment by lmgraves** [comment]
It is defined in the "Train TargetModel" block of cells
